spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: 123456
          url: jdbc:mysql://47.100.20.186:3306/dynamic?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
        tenant1_1:
          username: root
          password: 123456
          url: jdbc:mysql://47.100.20.186:3307/dynamic?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
        tenant1_2:
          username: root
          password: 123456
          url: jdbc:mysql://47.100.20.186:3308/dynamic?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
        tenant2_1:
          username: root
          password: 123456
          url: jdbc:mysql://47.100.20.186:3308/dynamic?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
        tenant2_2:
          username: root
          password: 123456
          url: jdbc:mysql://47.100.20.186:3308/dynamic?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.baomidou: debug